### ISSUE TITLE
Workflow: adding documents

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#131]
Quickfix:

- [x] unteres Plus von fokussiertem Element wird immer angezeigt. 
- [x] Plus nimmt Platz ein.
- [x] komplette Zeile ist anklickbar(ohne angezeigte Linie)

**Comment by elbotho** [comment]
First draft:
![image](https://user-images.githubusercontent.com/1258870/59692825-11e16300-91e6-11e9-9f06-1fdf56541a29.png)

While hovering an existing document: lines and **⊕**  above and below appear.
the lines have a height and the whole container (with the line and button) is a link (pointer, and hover effect).

if no document exists we might show a more verbose add-menu.

**Interactive demo**
https://www.figma.com/proto/0zbT7xzmbfbCNnDXt5ZJ7Hn1/Serlo-Redesign-Master?node-id=254%3A283&scaling=min-zoom&redirected=1

pros: only visual clutter when hovering, and more focus for the active document.
@inyono what do you think?

**Comment by inyono** [comment]
@elbotho I like that (gonna discuss that with Schul-Cloud tomorrow). Can you also add an nested example (e.g. an expanded spoiler)?

**Comment by elbotho** [comment]
Sure. I'd suggest the same thing. With nested documents still only the child get's the bars on top and button.

![image](https://user-images.githubusercontent.com/1258870/59761506-51b35380-9295-11e9-9320-b55148fde8be.png)

Btw. if we or Schul-Cloud prefer a more minimalistic version the idea would also work without the bar (only buttons).

**Comment by elbotho** [comment]
Some things turn out quite markup-heavy and with more content it might actually impact performance:

current state
```<div class="sc-iuJeZd fokRzV"><div class="sc-cmthru jJLsdi"><div class="add-trigger sc-esOvli jrstKK" name="rows"><svg width="24" height="24" viewBox="0 0 24 24" class="sc-hMFtBS HKRmu sc-bdVaJa kVtwHT"><path fill="currentcolor" d="M12,2 C6.48,2 2,6.48 2,12 C2,17.52 6.48,22 12,22 C17.52,22 22,17.52 22,12 C22,6.48 17.52,2 12,2 Z M16,13 L13,13 L13,16 C13,16.55 12.55,17 12,17 C11.45,17 11,16.55 11,16 L11,13 L8,13 C7.45,13 7,12.55 7,12 C7,11.45 7.45,11 8,11 L11,11 L11,8 C11,7.45 11.45,7 12,7 C12.55,7 13,7.45 13,8 L13,11 L16,11 C16.55,11 17,11.45 17,12 C17,12.55 16.55,13 16,13 Z"></path></svg></div></div></div>```

Maybe we can solve the whole thing with one `<a>` and something like this? 
```
a:after {
content: "+",
[…]
```

**Comment by elbotho** [comment]
@Knorrke [for devices that don't support hover](https://caniuse.com/#search=%40media%20hover) I'd suggest a simplified version with a global plus-button that always inserts after the currently selected document or at the end of the document as a fallback.
