### ISSUE TITLE
UI: Interactive plugins deactivated by default

### ISSUE THREAD

**Issue by elbotho** [edtr-io/edtr-io#149]
Interactive plugins (videos, applets, exercises) should be deactivated by default. 

Some users were confused by that so we add a clear "activate" button and grayout/blueout the plugin. A click on the button or the plugin activates it.

**Design draft:**
![image](https://user-images.githubusercontent.com/1258870/60723364-b926ff80-9f33-11e9-91f1-7996f7655a83.png)

**Comment by elbotho** [comment]
Ah just put the button in in the middle ;)

**Comment by metzgaria** [comment]
@elbotho can i have the css (or at least the colors)

**Comment by metzgaria** [comment]
we tried out blue, but in our opinion, in injections it wasn't clear that the content isn't clickable. 
Our suggestion: 

<img width="339" alt="overlay" src="https://user-images.githubusercontent.com/26926820/61580205-70646e80-ab0f-11e9-818e-8767dcb83502.PNG">

**Comment by Knorrke** [comment]
this is now implemented for sc-mc-exercises and input exercises (#208).
