### ISSUE TITLE
Handle focus / blur when using multiple editable Documents

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#150]
Global bottom toolbar doesn't work correctly when using multiple editable Documents

This occurs when there are multiple editors on page and two slate cells are focused. Might need to handle blur after all (namely: if one Document focuses something, blur all other Documents)

**Comment by Entkenntnis** [comment]
the Serlo Editor does not use multiple editable documents, therefore this is not part of our supported features currently
