### ISSUE TITLE
plugin-rows: improve dnd

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#188]
- Larger drop area (especially on left side since the drag handler is outside of the usual div)
- Handle larger documents (e.g. by restricting the preview's height)
- Sometimes it seems like the dnd doesn't work correctly (e.g. moves many documents around...)

**Comment by Knorrke** [comment]
additionally if possible: move between different rows-plugins

**Comment by metzgaria** [comment]
additional nice to have: show user where dropping is possible
