### ISSUE TITLE
plugin-text: use `\displaystyle` for block math formulas

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#192]

**Comment by Entkenntnis** [comment]
some more info? \textstyle, \scriptstyle, etc are working

**Comment by inyono** [comment]
The idea is to render our block math formulas as inline block formulas (since KaTeX isn't able to wrap block formulas) but insert `\displaystyle` automatically so that they look like a block math formula :)

**Comment by Entkenntnis** [comment]
This approach is working and will be availabe soon in a PR.

Remake: Shouldn't we start now to move block formulas into a separate plugin?

**Comment by Entkenntnis** [comment]
#198
