### ISSUE TITLE
documents lose focus

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#212]
At least on demo.edtr.io

**Comment by Knorrke** [comment]
This was working in 0.10.2, so probably a problem with slate upgrade...

**Comment by Knorrke** [comment]
Actually, its working in the deploy preview of #205 - https://deploy-preview-205--romantic-kare-b2be52.netlify.com/?path=/story/article-initial-state--editor and broken in #207 https://deploy-preview-207--romantic-kare-b2be52.netlify.com/?path=/story/article-initial-state--editor
So it seems like we have some assumptions about the state that don't hold true with the refactor.

**Comment by inyono** [comment]
Damn, that's on me then 😅 Gonna look into that
