### ISSUE TITLE
Two textplugins in add-menu

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#215]
![image](https://user-images.githubusercontent.com/26926820/65502140-82bda880-dec2-11e9-8672-ccb2d5fe18e7.png)
 Textplugin is in there twice

_Originally posted by @metzgaria in https://github.com/edtr-io/edtr-io/pull/214#issuecomment-534485981_

**Comment by inyono** [comment]
The reason for that is that the rows plugin is added twice, once with a custom registry, once with the legacy usage. The latter will probably removed with the next breaking change
