### ISSUE TITLE
Rewrite text-plugin and upgrade slate to v0.50+

### ISSUE THREAD

**Issue by Knorrke** [edtr-io/edtr-io#244]
Slate merged a massive pull request completely rewriting the editor. Key features for us are: 
- Full typescript rewrite with interface based data model.
- Hooks
- replaced immutable.js with simple json objects.

I think we will need to rewrite a lot of stuff of the current text-plugin, so maybe wait until 0.50.0 looks stable

**Comment by Entkenntnis** [comment]
Great news! And a lot of work to do ...

**Comment by inyono** [comment]
Btw: Slate 0.47 states don't work anymore (see https://github.com/ianstormtaylor/slate/issues/3272#issuecomment-562992645). So we definitely need a script to update our states in our database. Furthermore, we need to decide whether we want to migrate that or make that a breaking change in v1.0.0.

**Comment by elbotho** [comment]
More infos:
https://docs.slatejs.org/concepts/xx-migrating
