### ISSUE TITLE
history: commit focus

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#252]
We should commit focus in the history so that the cursor doesn't jump to the beginning of the text plugin.
- [ ] Commit editor focus
- [ ] Commit focus in text plugin state
- [ ] Remove editor focus on serialization
- [ ] Remove text plugin focus on serialization

**Comment by Knorrke** [comment]
One thing to watch out for, is that changing the focus shouldn't clear the redo stack. This will be problematic in the text plugin especially, since focus changes in slate are triggered as change events.

**Comment by kulla** [comment]
Done by https://github.com/edtr-io/edtr-io/pull/398
