### ISSUE TITLE
edtr-io: saving of applets & videos not working correctly

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#268]
`url: {notUri: "The input does not appear to be a valid Uri",…}
notUri: "The input does not appear to be a valid Uri"
regexNotMatch: "Applet-URL invalid. Use one of the form geogebra.org/m/id or ggbm.at/id"`

**Comment by metzgaria** [comment]
Video:  `{success: false, errors: {content: {uriInvalid: "Invalid type given. String expected",…}}}
success: false
errors: {content: {uriInvalid: "Invalid type given. String expected",…}}`

**Comment by metzgaria** [comment]
(article is working correctly)

**Comment by inyono** [comment]
Need to check the validators in the forms

**Comment by inyono** [comment]
see https://github.com/serlo/serlo.org/issues/196 https://github.com/serlo/serlo.org/issues/197
