### ISSUE TITLE
plugin/input-exercise: Can't handle fractions or decimals as exponent

### ISSUE THREAD

**Issue by Knorrke** [edtr-io/edtr-io#270]
The exercise on https://de.serlo.org/14069 has the expected result 1/3x^(-2/3), but this is not supported by the algebra.js library https://github.com/nicolewhite/algebra.js/issues/75
To test this, just log the following:
```
A.parse('1/3x^(-2/3)').toString() // output: 1/3x
A.parse('1/3x^(2/3)').toString() // output: 1/3x^2
```

**Comment by Knorrke** [comment]
https://guppy.js.org/site/examples/quiz/ uses https://github.com/kisonecat/math-expressions for this usecase, which seems to work quite well.

**Comment by Entkenntnis** [comment]
still relevant. `1/3x` is accepted as answer - but it's not correct.
