### ISSUE TITLE
Generalize DnD and expose as public API

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#274]
With #267, our DnD works pretty well. If we generalize that a little bit, we can expose that in `@edtr-io/editor-ui` so that plugins don't need to bring their own DnD-Library and end users have a consistent feeling.

Proposed behavior:
- Dragging is allowed between plugins of the same type (e.g. configurable in plugin configs. So you could, in theory, have multiple plugins that work with the same DnD context)
- File dropping should be configurable (i.e., either I can work with files myself or I allow to add plugins that can work with that)

**Comment by Entkenntnis** [comment]
in the new repo, this issue is not relevant anymore.
