### ISSUE TITLE
Drag preview in Chrome doesn't handle absolute positioned elements

### ISSUE THREAD

**Issue by Knorrke** [edtr-io/edtr-io#280]
When dragging the text-plugin while the absolute positioned bottom-toolbar is visible, then the drag preview will display all the plugins between the dragged and the bottom-toolbar as well

![dnd-chrome](https://user-images.githubusercontent.com/11499926/72728614-114ee780-3b8e-11ea-8ca7-c2f0a0b896d6.gif)

**Comment by Entkenntnis** [comment]
this still still the case.
