### ISSUE TITLE
plugin sc/mc or input exercise improvements

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#293]
- [ ] input exercise: When adding a new answer, cursor is in feedback field instead of answer field
- [ ] placeholder text for feedback field
- [x] sc/mc: cursor jumps to the beginning after each input
- [ ] input exercise: first answer should/could be correct per default 
- [x] sc/mc: mix answers in renderer

**Comment by Entkenntnis** [comment]
pretty much still relevant.
