### ISSUE TITLE
Missing i18n

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#300]
We missed some places where i18n isn't handled correctly (e.g. plugin toolbar, possibly other places, too)

**Comment by sstubbs** [comment]
This project looks amazing. How would you suggest i18n is handled until this is fixed if I want to use this?

**Comment by inyono** [comment]
Apart from the places mentioned above, i18n has been implemented in all official plugins. To customize i18n, you pass `i18n` with the labels, see e.g. [RowsPluginConfig](https://edtr.io/api-reference/plugin-rows/rowspluginconfig):
```ts
const rowsPlugin = createRowsPlugin({
  i18n: {
    addLabel: 'Add a fancy plugin'
  }
})
```
Similar to `theme`, this is merged with the default labels (so if you target English users, you don't have to specify the whole i18n object).

**Comment by sstubbs** [comment]
Ok great thanks for the help.

**Comment by inyono** [comment]
You're welcome. Feel free to get in touch again if you run into problems or something doesn't work as expected :)

**Comment by sstubbs** [comment]
Will do. Thank you very much. I'm trying to use this for our site at the moment to manage content and intend to use it for generated pdf files too.
