### ISSUE TITLE
When deleting an empty text plugin, Backspace key also triggers browser hotkeys

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#304]
I was editing an article at Serlo and wanted to delete some text via delete button. I think I deleted the whole text in THIS plugin (there was still text above) and therefore lost fokus of the whole dokument.
The next "DEL" caused my browser to ask me whether i want to leave the page without saving.

**Comment by inyono** [comment]
Steps to reproduce at https://demo.edtr.io:
- Add text plugin
- Focus the newly inserted text plugin
- Press backspace key
- Notice that the plugin was removed but the browser also tries to go back to the last visited space (might be a missing prevent default or something)
