### ISSUE TITLE
react-dnd-html5-backend error

### ISSUE THREAD

**Issue by markhats** [edtr-io/edtr-io#312]
Using the code in the 'Getting Started' doc with TypeScript, I'm getting the following error at runtime:

```
./node_modules/@edtr-io/core/dist/core.esm.js
Attempted import error: 'react-dnd-html5-backend' does not contain a default export (imported as 'HTML5Backend').
```
Code:
```
import React from 'react'

import { Editor } from '@edtr-io/core'
import { createTextPlugin } from '@edtr-io/plugin-text'
import { EditorPlugin } from '@edtr-io/plugin'

const textPlugin = createTextPlugin({
  placeholder: 'Hello world',
  registry: []
})

const plugins: Record<string, EditorPlugin<any, any>> = {
  text: textPlugin
}

const initialState = { plugin: 'text' }

class TextBoxPopoverContent extends React.Component<{}, {}> {
  constructor(props) {
    super(props)
  }

  render() {
    return (      
      <div>
        <Editor plugins={plugins} initialState={initialState} />
      </div>
    )
  }
}

export default TextBoxPopoverContent
```

**Comment by nikvdp** [comment]
I was running into the same issue after starting a new project with create-react-app. Was able to work around it by downgrading `react-dnd` and `react-dnd-html5-backend` to `10.0.0`. The [getting started guide](https://edtr.io/docs/getting-started) should probably be updated though, as the `yarn add` commands mentioned there don't install a working version.

@markhats try changing your package.json to match the below:
```
    "react-dnd": "^10.0.0",
    "react-dnd-html5-backend": "^10.0.0",
```

**Comment by markhats** [comment]
Thanks - that seems to work. I'm pretty sure it could be fixed by changing the follow line:

https://github.com/edtr-io/edtr-io/blob/3a848b2717849585650bc5246a48b391c54b3964/packages/public/core/src/editor.tsx#L20

to:
```
import { HTML5Backend } from 'react-dnd-html5-backend'
```

**Comment by inyono** [comment]
As @nikvdp said, the reason for that is that we currently use react-dnd v10. I created to follow up issues:
- To update the Getting Started guide to include the major version so that breaking changes don't break the guide: https://github.com/edtr-io/docs/issues/1.
- To update Edtr.io to use react-dnd v11: https://github.com/edtr-io/edtr-io/issues/313.

Let me know if you run into any other issues.
