### ISSUE TITLE
Some problems with importing types

### ISSUE THREAD

**Issue by elbotho** [edtr-io/edtr-io#317]
currently I use this construct to get the types for the plugins
``` tsx
import { StateTypeSerializedType } from '@edtr-io/plugin'
import { AnchorPluginState } from '@edtr-io/plugin-anchor/src/index'


export interface EdtrPluginAnchor {
  plugin: 'anchor'
  state: StateTypeSerializedType<AnchorPluginState>
}
```

~this works reasonably well for most types. ~

I had problems with:
- edtr state type returns as string this way…
- Importing HighlightPluginState triggers a type error, that's probably already happening in this repo (?)
- Was not able to extract Slate plugin types (like `a`, `math` or plain text node) 
- Was not able to find types for plugin 'Layout' ?
- Problem with `TextPluginState` 
- Waiting for equations to be on npm when it's finished

**Comment by inyono** [comment]
A general note beforehand: You should never need to import from `src/*`. Instead:
```tsx
import { AnchorPluginState } from '@edtr-io/plugin-anchor'
```
is the only supported import.

Now regarding your problems:
- "edtr state type returns as string this way…" Not sure what you mean by that. Can you give an example?
-  "Importing HighlightPluginState triggers a type error, that's probably already happening in this repo (?)" Not that I know of. Can you please give an example including the error message?
- "Was not able to extract Slate plugin types (like a, math or plain text node)" We do export those. See `NewElement` and its used types in https://github.com/edtr-io/edtr-io/blob/master/api/plugin-text.api.md.
- "Was not able to find types for plugin 'Layout'" Layout is a Serlo-internal plugin. We might need to expose that as an npm package with appropriate types if we want to use the same code in the redesign project.
- "Problem with `TextPluginState`" Namely?
- "Waiting for equations to be on npm when it's finished" Similarly to layout, equations is a Serlo-internal plugin at the moment.

**Comment by elbotho** [comment]
talking points:

- [ ] so the `StateTypeValueType<AnchorPluginState>` approach basically makes sense? ([see file](https://github.com/serlo/frontend/blob/e47e1ed1158c375d404d5f9b5f85fe28b73dca20/src/schema/edtr-io-types.ts))
- [ ] edtr-state type problem: let's talk about it. (example below)
- [x] highlight: seems to work now.
- [x] slate types: nice! works.
- [ ] layout and equations: does it make sense to expose them via npm? should I open an issue for that? (and where?)
- [ ] text plugin: `EdtrPluginText.state: ValueJSON` Not what I was expecting, maybe you can explain.

---

#### Edtr-State example:
content of spoiler plugin has this type: 
``` tsx
content: StateType<{
        plugin: string;
        state?: unknown;
    }, string, {
        ...;
    }>;
```
which results in `node.state.content` being type `string` for some reason.

**Comment by elbotho** [comment]
Thank you!
