### ISSUE TITLE
Video plugin improvements

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#330]
- [ ] Privacy wrapper
- [ ] Allow to customize normalization behavior

**Comment by elbotho** [comment]
PR to add support for custom parameters (subtitles) in the serlo frontend: https://github.com/serlo/frontend/pull/642

**Comment by metzgaria** [comment]
Should additional parameters already be possible?
Wasn't working in serlo.org/154847 if I understood the issue correctly. 
(See revision 194788)
@inyono

**Comment by inyono** [comment]
First: this is only done for the frontend and we didn't touch the Edtr.io core plugins so far (so no UI elements for that feature and it won't work in legacy serlo.org). Second: we only allow `cc_load_policy`, see https://github.com/serlo/frontend/pull/642/files#diff-a938a62ae99cf7f9d145d2452ff3f261d2d48bf6a15d622ce3ba545964780584R56-R57. If there are other video parameters you need, we can discuss whether we add allow them, too (This should be discussed in https://github.com/serlo/frontend, though).

**Comment by elbotho** [comment]
solved in serlo frontend for now
