### ISSUE TITLE
Render content of the Editor to another React component

### ISSUE THREAD

**Issue by quanphan2906** [edtr-io/edtr-io#335]
In React app, I have a component as below (abridged for the sake of the question):

`<form onSubmit={sendMessage}>`
           `<Editor plugins={plugins} InitialState={initialState} onChange={({ getDocument }) => handleChange({ getDocument })} />`
          ` <button>Send</button>`
`</form>`

Whenever the user submits, I want to get the current content of the Editor, render the content to another component and empty the Editor. How can I get the content from the Editor when the getDocument function only returns the serialized document, which is an object whose structure changes according the content of the Editor?

**Comment by inyono** [comment]
I'm not entirely sure if I understand your use case correctly, but here might be some pointers:

- To render an Edtr.io state, you can use the [`Renderer` component in `@edtr-io/renderer](https://edtr.io/api-reference/renderer/renderer) which needs the plugins and the state, so:
    ```tsx
    const state = getState() // here you'll retrieve the state from wherever you persisted it after the form submit.
    return <Renderer plugins={plugins} state={state} />
    ```
- To reset the editor state, you can pass a new `initialState` to `Editor`. So this could look something like this:
   ```.tsx
   function Form() { // Your React component that renders form and Editor
    const [initialState, setInitialState] = React.useState(someInitialStateYouWantToUse)
    
    function sendMessage(e) {
      // Persist the state somewhere and do whatever else you do on sendMessage right now

     // Here, you can reset the state to anything you'd like. If you want to use the same initialState as before, you want to create a copy of the object so that Edtr.io recognizes it as a new initial state.
      setInitialState({ ...initialState })
    }

    return (
      <form onSubmit={sendMessage}>
        <Editor plugins={plugins} InitialState={initialState} onChange={({ getDocument }) => handleChange({ getDocument })} />
        <button>Send</button>
      </form>
    )
  }
  ```

**Comment by quanphan2906** [comment]
Yup, it worked. Thank you for the timely response!
