### ISSUE TITLE
improve export of button styles

### ISSUE THREAD

**Issue by elbotho** [edtr-io/edtr-io#360]
For a table plugin we use both `AddButton` and `RemoveButton` styles from the editor.

- Could the internal styles be exported?
- Could the exported StyledComponents allow for additional styling to be applied?

**Comment by inyono** [comment]
At the moment, we only expose `AddButton` and `RemoveButton` internally. `RemoveButton` should already be possible to be extended via the usual styled-components primitives, e.g.
```tsx
const CustomRemoveButton = styled(RemoveButton)(/* custom styles */)
```
On the other hand, `AddButton` is a component that uses the hidden `AddButtonComponent` and can therefore not be styled directly. We could expose `AddButtonComponent`, too, then you'd only have to repeat the definition of https://github.com/edtr-io/edtr-io/blob/8e096cd56eb9c692530cc08b56580eedee76766e/packages/public/editor-ui/src/interactive-answer-component.tsx#L21

Alternatively, we could add a optional `Component` prop to `AddButton` that defaults to `AddButtonComponent`.
