### ISSUE TITLE
Remove theme from plugin config

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#374]
Limitations & follow-ups after #373 refactoring:

- We no longer need to pass the theme to config, since that is handled by the plugins themselves. Remove that functionality with next major release.
- ~Use case: "dynamic" state handling (e.g. state dependent on state). We Should find a workaround for that. See remaining usages of `config` in `create*Plugin`.~

**Comment by Entkenntnis** [comment]
We will refactor config in the frontend as needed and consider the changes that happened in the last months.

This issue is likely outdated.
