### ISSUE TITLE
☂️  Umbrella Issue: 3.0.0

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#376]
Current list of breaking changes that should be addressed in the next major version:

- Remove deprecated exports, e.g. #374, #375.
- Drop Node v12 support. 
- Update peer dependencies.
- Maybe pure ESM.
- Maybe React v18.

**Comment by Entkenntnis** [comment]
in the new repo, edtr-io supports esm dependencies and runs von react v18.
