### ISSUE TITLE
React v18

### ISSUE THREAD

**Issue by inyono** [edtr-io/edtr-io#378]
We now use React v18 internally and everything seems to work as expected without breaking changes. We should review the new features, though, to see if they are relevant for us. See https://reactjs.org/blog/2022/03/29/react-v18.html.

**Comment by inyono** [comment]
react-hotkeys seems to cause issues, though. Need to investigate.

**Comment by Entkenntnis** [comment]
edtr-io is running with react v18 in the frontend
