### ISSUE TITLE
isEmpty not working for rows

### ISSUE THREAD

**Issue by elbotho** [edtr-io/edtr-io#384]
A rows plugin with an empty text plugin return false for `isEmpty(rowPluginId)(store.getState())`

**Comment by inyono** [comment]
We didn't implement `isEmpty` for rows since an empty rows plugin is kinda weird from an UX-perspective (especially at the root).

I could add a selector `isRowsEmpty()` to `@edtr-io/plugin-rows` that checks if all children are empty. Is this something that you could use for your use case?

**Comment by elbotho** [comment]
@inyono I think that would work very well 👍
