### ISSUE TITLE
plugin-text: Links spanning over math elements not editable

### ISSUE THREAD

**Issue by metzgaria** [edtr-io/edtr-io#89]
- [x] When inserting the URL in the overlay and pressing "Enter", a new line begins and the link is splitted
- [ ] When you have more than one row you can't edit/delete links via buttons

**Comment by Knorrke** [comment]
First one seems to be fixed in current master. 

Regarding the second issue: You mean, a link that spans multiple text-rows in the same plugin? This works for me, however I can see the described behavior, if theres a math formula inside of the linked text, (independent from the length).
