### ISSUE TITLE
Add cut/copy/paste actions to reducer

### ISSUE THREAD

**Issue by Knorrke** [edtr-io/edtr-io#9]

**Comment by kulla** [comment]
no idea what this means -> closing :smile: (reopen if needed)

**Comment by Knorrke** [comment]
This was e.g. for copy/paste functionality of content or multiple rows etc. To implement the behaviour the reducer needs Copy and paste actions that handle the store transformation (and are undo-able). 

We had that at some point for single plugins but it was more complicated with e.g. selecting over multiple text plugins so iirc it is still todo. Feel free to track this in new issues however you want, though :)
